# coding=utf8

import argparse
import re
import textwrap

parser = argparse.ArgumentParser(description='Sanitizes text.')
parser.add_argument('--input', metavar='input_filename', type=str,
                           help='input file', required=True)
parser.add_argument('--output', metavar='output_filename', type=str,
                           help='output file', required=True)
parser.add_argument('--width', metavar='number_of_columns', type=int,
                           help='wrap paragraphs to tdis width', default=60)
args = parser.parse_args()
print args

input_filename = args.input
output_filename = args.output
width = args.width

LETTER = (
    u'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz' +
    u'ÀÁÃÊÍÒÔÙÚàáâãèéêìíòóôõùúýĂăĐđĩũƠơƯự̀́̃̉ẠạẢảẤấẦầẩẫẬậẮắằẳẵẶặẸẹẻẽẾếỀềỂểễệ' +
    u'ỉịọỏỐốỒồỔổỗộớờởỡợỤụủỨứỪừửỮữựỳỵỷỹư')
LET = '[' + LETTER + ']'
NOTLET = '[^(' + LETTER + ']'

def IsLetter(c):
  return re.match(LET, c)

def Sanitize(line):
  line = line.replace('\t', ' ')
  line = re.sub(' +', ' ', line)
  line = re.sub('^ ', '', line)
  line = re.sub(' $', '', line)
  line = re.sub('^"', '``', line)
  line = re.sub(' "', ' ``', line)
  line = re.sub(u'“', '``', line)
  # The digit exclusion makes sure that dimensions (in inch) don't get coverted
  # to quotes. For example: 11" x 8.5".
  line = re.sub('[^0-9]"$', "''", line)
  line = re.sub('[^0-9]" ', "'' ", line)
  line = re.sub(u'”', "''", line)
  return line

def LatexSanitize(line):
  # '\\' should be handled first, otherwise it may double escape the backslash
  # character generated by another line.
  line = line.replace('\\', '\\textbackslash')

  line = line.replace('\x0c', '\\newpage\n\n')
  line = line.replace('&', '\\&')
  line = line.replace('%', '\\%')
  line = line.replace('$', '\\$')
  line = line.replace('#', '\\#')
  line = line.replace('_', '\\_')
  line = line.replace('{', '\\{')
  line = line.replace('}', '\\}')
  line = line.replace('~', '\\textasciitilde{}')
  line = line.replace('^', '\\textasciicircum{}')
  line = line.replace('^', '\\textasciicircum{}')
  line = line.replace('...', '\\ldots{}')
  line = line.replace(u'…', '\\ldots{}')
  return line


reader = open(input_filename)
writer = open(output_filename, 'w')
chars = set()
for line in reader:
  line = line.decode('utf8')
  for c in line:
    if not IsLetter(c):
      chars.add(c)
  line = Sanitize(line)
  line = LatexSanitize(line)
  writer.write(textwrap.fill(line, width).encode('utf8'))
  writer.write('\n\n')

for a in sorted(chars):
  print '%s %s' % (repr(a), a)
print ''.join(sorted(chars))

reader.close()
writer.close()

