# coding=utf8

import argparse
import re
import textwrap
import unicodedata

LETTER = (
    u'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz' +
    u'ÀÁÃÊÍÒÔÙÚàáâãèéêìíòóôõùúýĂăĐđĩũƠơƯựẠạẢảẤấẦầẩẫẬậẮắằẳẵẶặẸẹẻẽẾếỀềỂểễệ' +
    u'ỉịọỏỐốỒồỔổỗộớờởỡợỤụủỨứỪừửỮữựỳỵỷỹưỜỞỰ')
LET = '[' + LETTER + ']'
NOTLET = '[^(' + LETTER + ']'


def IsLetter(c):
  return re.match(LET, c)


def Sanitize(line):
  line = line.replace('\t', ' ')
  line = line.replace('\r', '')
  line = re.sub(' +', ' ', line)
  line = re.sub('^ ', '', line)
  line = re.sub(' $', '', line)
  return line


def SanitizeLatex(line):
  # '\\' should be handled first, otherwise it may double escape the backslash
  # character generated by another line.
  line = line.replace('\\', '\\textbackslash')

  line = re.sub('^________________[\r\n]*$', '\n\n\\\\newpage\n\n', line)
  line = re.sub('^"', '``', line)
  line = re.sub(' "', ' ``', line)
  line = re.sub(u'“', '``', line)
  # The digit exclusion makes sure that dimensions (in inch) don't get converted
  # to quotes. For example: 11" x 8.5".
  line = re.sub('([^0-9])"$', "\\1''", line)
  line = re.sub('([^0-9])" ', "\\1'' ", line)
  line = re.sub(u'”', "''", line)

  line = line.replace('\x0c', '\n\n\\newpage\n\n')
  line = line.replace('&', '\\&')
  line = line.replace('%', '\\%')
  line = line.replace('$', '\\$')
  line = line.replace('#', '\\#')
  line = line.replace('_', '\\_')
  line = line.replace(u'–', '--')
  line = line.replace('{', '\\{')
  line = line.replace('}', '\\}')
  line = line.replace(u'‘', '`')
  line = line.replace(u'’', "'")
  line = line.replace('~', '\\textasciitilde{}')
  line = line.replace('^', '\\textasciicircum{}')
  line = line.replace('^', '\\textasciicircum{}')
  line = line.replace('...', '\\ldots{}')
  line = line.replace(u'…', '\\ldots{}')
  line = line.replace(u'✝', '\\dag{}')
  return line


def NormalizeCombinedCharacters(line):
  line = unicodedata.normalize('NFC', line)
  output = ''
  for c in line:
    if ord(c) >= 0x300 and ord(c) <= 0x36F:
      diacritic = '\\u%04x\\u%04x' % (ord(output[-1]), ord(c))
      print 'Unknown combining diacritics %s in %s' % (diacritic, line)
    output += c
  return output


def Main(input_filename, output_filename, width, normalize_only):
  reader = open(input_filename)
  writer = open(output_filename, 'w')
  chars = set()
  output_blank_line = True
  for line in reader:
    line = line.decode('utf8')
    line = NormalizeCombinedCharacters(line)
    if normalize_only:
      writer.write(line.encode('utf8'))
      continue
    for c in line:
      if not IsLetter(c):
        chars.add(c)
    line = Sanitize(line)
    line = SanitizeLatex(line)
    if not line.strip():
      if  output_blank_line:
        line = '~'
        output_blank_line = False
    else:
      output_blank_line = True

    for part in re.split('[\n\r]+', line):
      if part:
        writer.write(textwrap.fill(part, width).encode('utf8'))
        writer.write('\n\n')

  for a in sorted(chars):
    print '%s %s' % (repr(a), a)
  print ''.join(sorted(chars))

  reader.close()
  writer.close()

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Sanitizes text.')
  parser.add_argument('--input', metavar='input_filename', type=str,
                      help='input file', required=True)
  parser.add_argument('--output', metavar='output_filename', type=str,
                      help='output file', required=True)
  parser.add_argument('--width', metavar='number_of_columns', type=int,
                      help='wrap paragraphs to this width', default=60)
  parser.add_argument('--normalize_only', dest='normalize_only',
                      action='store_true')

  args = parser.parse_args()
  print args

  input_filename = args.input
  output_filename = args.output
  width = args.width
  normalize_only = args.normalize_only

  Main(input_filename, output_filename, width, normalize_only)
